# Generated by Django 4.0.4 on 2022-06-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('PI', 'Pizza'), ('PA', 'Pâte'), ('SA', 'Salade'), ('DE', 'Dessert')], default='PI', max_length=2)),
                ('ingredients', models.CharField(max_length=400)),
                ('prix', models.FloatField(default=0)),
                ('vegetarienne', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
